//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaCourtier.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointments
    {
        public int idAppointment { get; set; }

        [Required(ErrorMessage = "Selectionne date et heure")]
        [Display(Name = "Date et heure")]
        [DataType(DataType.DateTime)]
        public System.DateTime dateHour { get; set; }

        [Required(ErrorMessage = "Un motif explicite")]
        [Display(Name = "Motif")]
        public string subject { get; set; }

        [Required(ErrorMessage = "Le nom du courtier")]
        [Display(Name = "Nom du COURTIER")]
        public int idCustomer { get; set; }

        [Required(ErrorMessage = "Le nom du CLIENT")]
        [Display(Name = "Nom du CLIENT")]
        public int idBroker { get; set; }

        
        public virtual Brokers Brokers { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
