//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaCourtier.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Brokers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brokers()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int idBroker { get; set; }

        [Required(ErrorMessage ="Un Nom")]
        [Display(Name ="Nom")]
        public string lastname { get; set; }

        [Required(ErrorMessage = "Un prenom")]
        [Display(Name = "Prénom")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string mail { get; set; }

        [Required(ErrorMessage = "Required")]
        [MinLength(10,ErrorMessage ="Entrez un numero telephone valide")]
        [Phone]
        [Display(Name = "N° Mobile")]
        public string phoneNumber { get; set; }

        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}
