//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaCourtier.Models
{
    public class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int idBroker { get; set; }
        public int idAppointment { get; set; }
        public int idCustomers{ get; set; }

        public virtual Brokers Brokers { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Appointments Appointments { get; set; }
    }
}